// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0bILaWHg8QXuwl3Fhfht3BQnYLgTkWUk',
    appId: '1:879703010053:web:1fe4e4476ab1680a67a56c',
    messagingSenderId: '879703010053',
    projectId: 'tf-unions',
    authDomain: 'tf-unions.firebaseapp.com',
    storageBucket: 'tf-unions.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0bILaWHg8QXuwl3Fhfht3BQnYLgTkWUk',
    appId: '1:879703010053:web:1ff531e0797a3fe167a56c',
    messagingSenderId: '879703010053',
    projectId: 'tf-unions',
    authDomain: 'tf-unions.firebaseapp.com',
    storageBucket: 'tf-unions.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz9RUYj3bA5GChVD_0KiGbXa_wIH9VU2s',
    appId: '1:879703010053:ios:e1beb2bc77c42ba567a56c',
    messagingSenderId: '879703010053',
    projectId: 'tf-unions',
    storageBucket: 'tf-unions.firebasestorage.app',
    androidClientId: '879703010053-a8er8rrdojiu7aloe9f99v3drsemee4o.apps.googleusercontent.com',
    iosClientId: '879703010053-617cr8s9h8plaos5vbe98608br26ptar.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfNews',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz9RUYj3bA5GChVD_0KiGbXa_wIH9VU2s',
    appId: '1:879703010053:ios:e1beb2bc77c42ba567a56c',
    messagingSenderId: '879703010053',
    projectId: 'tf-unions',
    storageBucket: 'tf-unions.firebasestorage.app',
    androidClientId: '879703010053-a8er8rrdojiu7aloe9f99v3drsemee4o.apps.googleusercontent.com',
    iosClientId: '879703010053-617cr8s9h8plaos5vbe98608br26ptar.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfNews',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAZ8yqqEQxefJGjUXcWoRqELQ5gD6xMFI',
    appId: '1:879703010053:android:2139f411f739930767a56c',
    messagingSenderId: '879703010053',
    projectId: 'tf-unions',
    storageBucket: 'tf-unions.firebasestorage.app',
  );
}
